name = "inference-playground"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/output/client"
binding = "ASSETS"



